version: "3"
services:
  mysql:
    container_name: mysql5.7
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - /data/tool/mysql/data:/var/lib/mysql:rw
      - /data/tool/mysql/conf:/etc/mysql:rw
      - /data/tool/mysql/log:/var/log/mysql:rw
    ports:
      - "3336:3306"