version: "3"
services:
  mysql:
    container_name: mysql5.7
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./data/tool/mysql5.7/data:/var/lib/mysql
      - ./data/tool/mysql5.7/conf:/etc/mysql
      - ./data/tool/mysql5.7/log:/var/log/mysql
    ports:
      - "3306:3306"